### ISSUE TITLE
Request for feature 

### ISSUE THREAD

**Issue by TheBlueFireFox** [RememberTheAir/GroupButler#16]
Is it possible to implement a warning system for writing arab messages? And on the second or tired time ban them?
Thank you for your work and the really practical bot

Adrian

**Comment by RememberTheAir** [comment]
Yes sure it's possible to implement.

I was thinking to add a way to set how many warns an user can get when sending a not allowed media/writing in arab characters.

And, RTL and arab settings miss an option to choose if ban or kick. I'll try to add them as soon as I can

**Comment by TheRedFireFox** [comment]
Thank you very much XD
If I may suggest something more:
Is it possible for the bot to have an additional channel (or group) in that it logs it's activity, so that it's possible to overview what it did during the night?

Adrian

**Comment by RememberTheAir** [comment]
@TheRedFireFox Sure, you can see in config.lua, there is a field called "log_chat" or something like that

It's meant to be a random log chat where post what you need to see

To post things in the log chat, you can use:
api.sendLog(text you want to send)

You can call this function from everywhere, and the bot will send to this chat what you need to send

**Comment by sirmarita** [comment]
I would really like the bot to be *"invisible"* in the group, this can be achieved by removing all the commands. Thus meaning when an Admin sends a trigger the bot responds, or when a user sends a trigger (like custom commands) the bot also responds. I would really like this feature. All functions will remain as it was but only removing commands thus making it possible for no group commands. Or if anyone is running a clone that has no command please don't hesitate to PM with its username on my telegram @sirmarita, otherwise thanks again for good job. The bot is pretty awesome

**Comment by kamikazechaser** [comment]
@sirmarita Check out my fork. And check out the the bot too. I use "silent" commands.

**Comment by sirmarita** [comment]
Have checked it out but seems not to be responding even if I type commands in the group

**Comment by kamikazechaser** [comment]
I was working on it, Its now online.

**Comment by sirmarita** [comment]
Awesome.

On Tue, 14 Jun 2016 4:07 pm Mohammed Sohail, <notifications@github.com>
wrote:

> I was working on it, Its now online.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/RememberTheAir/GroupButler/issues/16#issuecomment-225875206>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS7p9BqCPY6y81f-qX9EnaEFr0EPKzcIks5qLqekgaJpZM4IjH2W>
> .
>
-- 

Your Faithfull

Marita Edwin.
