### ISSUE TITLE
Error when requesting backup file

### ISSUE THREAD

**Issue by mmmTelegram** [RememberTheAir/GroupButler#251]
![2017-11-10 01_51_25-telegram 212150](https://user-images.githubusercontent.com/33640844/32754249-bed3c40a-c8d8-11e7-8910-0aef94a2145c.png)

An #error occurred.
./lua/plugins/backup.lua:12: bad argument #1 to 'encode' (expected 1 argument)
stack traceback:
 [C]: in function 'encode'
 ./lua/plugins/backup.lua:12: in function 'save_data'
 ./lua/plugins/backup.lua:59: in function 'gen_backup'
 ./lua/plugins/backup.lua:105: in function <./lua/plugins/backup.lua:90>
 [C]: in function 'xpcall'
 ./lua/main.lua:107: in function <./lua/main.lua:61>
 (...tail calls...)
 ./polling.lua:46: in main chunk
 [C]: in ?
en
/snap

**Comment by RememberTheAir** [comment]
mmmm, it looks like an incompatibility with the `cjson` module. While `dkjson` allows to define wheter the representation of the table should be indented or not, I guess `cjson` doesn't.

Since `JSON` is a local value, you can safely replace `cjson` with `dkjson` [here](https://github.com/RememberTheAir/GroupButler/blob/master/lua/plugins/backup.lua#L4) as a quick fix

Note that the dkjson module need to be installed

**Comment by NotAFile** [comment]
I guess the formatting can just be removed? Users that want to edit the file can just reformat it themselves or use an online tool.

**Comment by NotAFile** [comment]
@RememberTheAir someone™ should just write a commit removing it

**Comment by RememberTheAir** [comment]
@NotAFile but who

**Comment by mmmTelegram** [comment]
Thank you very much for your help
